dependencies:
 - name: binderhub
   # NOTE: when binderhub version is upgraded, upgrade chart version too (Chart.yaml)
   version: 0.2.0-n242.h87e78af
   repository: https://jupyterhub.github.io/helm-chart
