binderhub:
  resources:
    requests:
      cpu: 0
      memory: 0

  config:
    BinderHub:
      debug: true
      # 192.168.99.100 is minikube ip
      hub_url: http://192.168.99.100:30123
      use_registry: false

  service:
    type: NodePort
    nodePort: 30124

  imageCleaner:
    enabled: false

  jupyterhub:
    debug:
      enabled: true
    hub:
      cookieSecret: "29195074ffd6cae79ed3dcb7483f65c098275b172a4757cc998c00dcc63ff173"
      authenticatePrometheus: false
      shutdownOnLogout: true
      services:
        binder:
          # 192.168.99.100 is minikube ip
          url: http://192.168.99.100:30124
          oauth_redirect_uri: "http://192.168.99.100:30123/services/binder/oauth_callback"
          oauth_client_id: "binder-oauth-client-dev"
          apiToken: "6e5252a4ef9f19554cfffd970270e144e4dcca1520b9c6bb6c6f412743cbea7a"
      resources:
        requests:
          cpu: 0
          memory: 0

    proxy:
      secretToken: "790fd9f44ea71a380294cb1d3b483cef1b3d4cb0fe9335132c56661e85b6ab69"
      https:
        enabled: false
      service:
        type: NodePort
        nodePorts:
          http: 30123
      chp:
        resources:
          requests:
            memory: 0
            cpu: 0

    auth:
      admin:
        users:
          - admin
      state:
        cryptoKey: "696dc77c0a950f42710b7e5694b721dfe9298c047e204854fea5cff6cbb9eb98"

    singleuser:
      cpu:
        guarantee: 0
      memory:
        guarantee: 0
      storage:
        capacity: 5Gi

    scheduling:
      userScheduler:
        enabled: false
      podPriority:
        enabled: false
      userPlaceholder:
        enabled: false
