kind: ConfigMap
apiVersion: v1
metadata:
  name: persistent-bhub-templates
  labels:
    app: persistent-bhub
    component: hub
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  {{- (.Files.Glob "files/jupyterhub/templates/*").AsConfig | nindent 2 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: persistent-bhub-styles
  labels:
    app: persistent-bhub
    component: hub
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  persistent_bhub.css: |-
    {{- .Files.Get "files/jupyterhub/persistent_bhub.css" | nindent 4 }}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: persistent-bhub-config
  labels:
    app: persistent-bhub
    component: hub
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  persistent_bhub_config.py: |-
    {{- .Files.Get "files/jupyterhub/persistent_bhub_config.py" | nindent 4 }}
